version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    restart: always
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    expose:
      - "8000"
    links:
      - db:db
      - redis:redis
    volumes:
      - /home/django/app
      - static:/home/django/app/static
    command: /home/django/.local/bin/gunicorn back.wsgi:application -b :8000
    depends_on:
      - db

  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - type: volume
        source: static
        target: /var/www/static:ro
        read_only: true
    ports:
      - "80:80"
    depends_on:
      - web
    links:
      - web:web

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: ./back
    command: /usr/local/bin/celery -A back worker -l info
    depends_on:
      - redis

  celery-beat:
    build: ./back
    command: /usr/local/bin/celery -A back beat -l info
    depends_on:
      - redis

volumes:
  web-django1:
  static:
  pgdata:
