version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - global

  web:
    image: chiefonboarding/chiefonboarding:latest
    restart: always
    expose:
      - "8000"
    build:
      dockerfile: ./Dockerfile-dev
      context: ./back/
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=somethingsupersecret
      - BASE_URL=http://0.0.0.0:3000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DEFAULT_FROM_EMAIL=michael@elloe.io
    volumes:
      - ./back:/app
    depends_on:
      - db
    networks:
      - global

caddy:
    image: caddy:2.3.0-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - global

volumes:
  pgdata:
  caddy_data:
  caddy_config:

networks:
  global:
