databases:
  - name: chiefonboardingdb
    databaseName: chiefonboardingdb
    ipAllowList: []

services:
  - type: web
    name: chiefonboarding
    env: python
    buildCommand: "pip install -r requirements.txt && cd back && python manage.py collectstatic --no-input && python manage.py createcachetable && python manage.py migrate"
    startCommand: "gunicorn --chdir back back.wsgi:application"
    envVars:
      - fromGroup: chief-default
      - key: DATABASE_URL
        fromDatabase:
          name: chiefonboardingdb
          property: connectionString
      - key: ACCOUNT_EMAIL
        sync: false
      - key: ACCOUNT_PASSWORD 
        sync: false
      - key: BASE_URL 
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false

  - type: worker
    name: django-q
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python back/manage.py qcluster"
    envVars:
      - fromGroup: chief-default
      - key: DATABASE_URL
        fromDatabase:
          name: chiefonboardingdb
          property: connectionString
      - key: BASE_URL 
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false

envVarGroups:
  - name: chief-default
    envVars:
      - key: SECRET_KEY
        generateValue: true
